// ============================================================
// AI活用ダッシュボード — データ定義
// 更新はこのファイルの値を変更 → git push で反映
// ============================================================

const DASHBOARD_DATA = {
  lastUpdated: "2026/3/17",
  manager: "Takuma Sugata",
  title: "AIインテグレーター",

  // ヒーローエリアの数字
  summary: {
    toolsInProduction: 1,
    totalProjects: 12,
    categories: 6,
    maxReduction: 96
  },

  // Section 2: 効果・成果（Before/After）
  results: [
    {
      name: "業務マニュアル自動作成ツール",
      icon: "document",
      status: "live",
      statusLabel: "運用中",
      description: "引継ぎMTGの文字起こしをアップロードするだけで、業務マニュアルを自動生成",
      before: "手作業でマニュアルを作成（1件あたり2〜3時間）",
      after: "ファイルをアップロードするだけで自動生成（約5分）",
      savedTime: "1件あたり約2.5時間削減",
      savedTimeValue: null // 月間削減時間（計測後に設定）
    },
    {
      name: "社内ナレッジAIチャットボット",
      icon: "chat",
      status: "building",
      statusLabel: "構築中",
      description: "社内ルール・業務ノウハウ・ツール操作方法をAIチャットで即座に回答",
      before: "マニュアルを探す・詳しい人に聞く（数十分かかることも）",
      after: "AIに質問するだけで即回答（数秒）",
      savedTime: "問い合わせ対応・検索時間を大幅削減",
      savedTimeValue: null
    },
    {
      name: "チャット通知自動化システム",
      icon: "bell",
      status: "testing",
      statusLabel: "テスト中",
      description: "Chatworkのメッセージを自動でTeamsに通知。30分未対応なら自動返信",
      before: "Chatworkを定期的に確認 → 見逃し・対応遅延のリスク",
      after: "Teamsに自動通知 + 未対応時は自動返信でクライアント安心",
      savedTime: "クライアント対応の見逃しゼロ化",
      savedTimeValue: null
    }
  ],

  // Section 3: AI化提案カテゴリ
  proposals: [
    {
      category: "経理・会計",
      icon: "calculator",
      items: [
        { task: "請求書の自動チェック", desc: "金額・日付・宛名の整合性をAIが自動で確認" },
        { task: "仕訳入力の補助", desc: "証憑データから勘定科目を自動で推測・提案" },
        { task: "経費精算の自動分類", desc: "経費明細を科目ごとに自動で振り分け" },
        { task: "月次レポート自動生成", desc: "会計データから報告用レポートを自動作成" }
      ]
    },
    {
      category: "人事・労務",
      icon: "people",
      items: [
        { task: "勤怠データの自動集計", desc: "出退勤データの集計・異常値チェックを自動化" },
        { task: "入退社チェックリスト自動生成", desc: "入退社に必要な手続きリストを自動作成" },
        { task: "給与計算の事前チェック", desc: "計算結果の異常値・変動をAIが事前に検出" },
        { task: "社員情報の更新通知", desc: "変更が必要な情報を自動で検出・通知" }
      ]
    },
    {
      category: "IT・システム",
      icon: "monitor",
      items: [
        { task: "社内FAQボット", desc: "よくある質問にAIが自動で回答（実績あり）" },
        { task: "ツール操作ガイドの自動応答", desc: "「○○の使い方」と聞くだけで手順を表示" },
        { task: "アカウント発行手順の自動化", desc: "申請から発行までのフローを自動化" },
        { task: "障害・エラー対応ガイド", desc: "エラーメッセージから対処法を自動提示" }
      ]
    },
    {
      category: "営業・CS",
      icon: "phone",
      items: [
        { task: "チャット通知の自動化", desc: "クライアントからのメッセージを即座にTeams通知（実績あり）" },
        { task: "議事録の自動作成", desc: "会議の文字起こしから議事録を自動生成" },
        { task: "提案書のドラフト自動生成", desc: "要件をもとに提案書の下書きをAIが作成" },
        { task: "案件マッチングの自動化", desc: "案件要件と人材スキルを自動照合（制作中）" }
      ]
    },
    {
      category: "総務・法務",
      icon: "folder",
      items: [
        { task: "契約書のチェックポイント抽出", desc: "契約書から確認すべき条項をAIが自動抽出" },
        { task: "社内規定の検索AI", desc: "「○○のルールは？」と聞くだけで該当規定を表示" },
        { task: "備品管理の自動化", desc: "在庫状況の確認・発注タイミングの通知を自動化" },
        { task: "申請書類のテンプレート自動生成", desc: "申請内容に応じた書類を自動で下書き" }
      ]
    },
    {
      category: "共通業務",
      icon: "gear",
      items: [
        { task: "メール文面の自動作成", desc: "要件を入力するだけでビジネスメールを自動生成" },
        { task: "データ集計レポートの自動化", desc: "Excelデータから集計・グラフ付きレポートを自動作成" },
        { task: "定型業務のワークフロー化", desc: "毎回同じ手順の作業を自動化・省力化" },
        { task: "業務マニュアルの自動作成", desc: "業務内容を伝えるだけでマニュアルを自動生成（実績あり）" }
      ]
    }
  ],

  // Section 5: プロジェクト一覧
  projects: [
    {
      name: "業務マニュアル自動作成ツール",
      nameEn: "Auto Manual Generator",
      description: "文字起こしをアップロードするだけで業務マニュアルを自動生成",
      descriptionEn: "Automatically generates operation manuals from meeting transcripts",
      status: "live",
      statusLabel: "運用中",
      statusLabelEn: "Live",
      progress: 100,
      url: "https://udify.app/workflow/j9fyHZH2mZ5UzntX",
      detail: {
        overview: "引継ぎMTGの文字起こしデータから、見出し・手順・注意事項を整理した業務マニュアルを自動生成するAIツール。生成されたマニュアルはWordファイル（.docx）として出力され、指定したSharePointフォルダに自動格納される。",
        overviewEn: "An AI tool that automatically generates structured operation manuals (headings, procedures, notes) from handover meeting transcripts. Output as Word (.docx) files, automatically saved to SharePoint.",
        background: "引継ぎMTG後に手作業でマニュアルを作成していたが、1件あたり2〜3時間かかっており、担当者の大きな負担になっていた。品質のばらつきも課題だった。",
        backgroundEn: "Creating manuals manually after handover meetings took 2-3 hours each, placing a heavy burden on staff. Quality inconsistency was also an issue.",
        targetUsers: "社内の業務担当者（引継ぎ業務を行う社員）",
        targetUsersEn: "Internal staff handling handover tasks",
        tools: ["Dify", "LLM", "Python", "SharePoint"],
        impact: {
          before: "手作業でマニュアルを作成（1件あたり2〜3時間）",
          beforeEn: "Manual creation by hand (2-3 hours per document)",
          after: "ファイルをアップロードするだけで自動生成（約5分）",
          afterEn: "Auto-generated by uploading a file (~5 min)",
          savedTime: "1件あたり約2.5時間削減",
          savedTimeEn: "~2.5 hours saved per document"
        },
        period: "2026年3月1日〜3月3日",
        periodEn: "Mar 1 – Mar 3, 2026"
      },
      history: [
        { text: "Difyワークフロー設計・構築", textEn: "Dify workflow design & build", done: true },
        { text: "LLMプロンプト設計・調整", textEn: "LLM prompt engineering", done: true },
        { text: "Pythonコード実装（テキスト整形）", textEn: "Python implementation (text formatting)", done: true },
        { text: "テスト・品質確認・納品", textEn: "Testing, QA & delivery", done: true }
      ],
      nextAction: "完成・納品済み",
      nextActionEn: "Completed & delivered",
      lastUpdated: "2026/3/3",
      lastUpdatedNote: "完成・納品",
      lastUpdatedNoteEn: "Completed & delivered"
    },
    {
      name: "社内ナレッジAIチャットボット",
      nameEn: "Internal Knowledge AI Chatbot",
      description: "社内ルール・業務ノウハウをAIチャットで即座に検索・回答",
      descriptionEn: "Instantly search and answer internal rules & business know-how via AI chat",
      status: "building",
      statusLabel: "構築中",
      statusLabelEn: "Building",
      progress: 80,
      url: null,
      detail: {
        overview: "社内ルール・業務ノウハウ・ツール操作方法などを、AIチャットで質問するだけで即座に回答を得られるシステム。4ファイル体制のナレッジベースを構築し、Teamsから利用可能。",
        overviewEn: "A system where employees can ask questions via AI chat and get instant answers about internal rules, business know-how, and tool usage. Built with a 4-file knowledge base, accessible from Teams.",
        background: "社内ルールや手続きについて「詳しい人に聞く」「マニュアルを探す」ことに数十分かかるケースが多く、特に新人支援で非効率が目立っていた。",
        backgroundEn: "Finding answers about internal rules often took tens of minutes—asking colleagues or searching manuals. Especially inefficient for onboarding new staff.",
        targetUsers: "社員全員",
        targetUsersEn: "All employees",
        tools: ["Dify", "LLM", "Azure AD", "Teams"],
        impact: {
          before: "マニュアルを探す・詳しい人に聞く（数十分かかることも）",
          beforeEn: "Search manuals or ask colleagues (often takes tens of minutes)",
          after: "AIに質問するだけで即回答（数秒）",
          afterEn: "Ask AI and get instant answers (seconds)",
          savedTime: "問い合わせ対応・検索時間を大幅削減",
          savedTimeEn: "Significant reduction in inquiry & search time"
        },
        period: "2026年3月3日〜",
        periodEn: "Mar 3, 2026 –"
      },
      history: [
        { text: "Difyチャットボット構築（フェーズ1〜4）", textEn: "Dify chatbot build (Phase 1-4)", done: true },
        { text: "Azure認証・Teams連携設定", textEn: "Azure AD auth & Teams integration", done: true },
        { text: "ナレッジ3ファイル作成・Dify登録", textEn: "3 knowledge files created & registered in Dify", done: true },
        { text: "社内ポータルナレッジ7セクション追加", textEn: "Added 7 sections of portal knowledge", done: true },
        { text: "社内アンケートQ&A 35項目抽出", textEn: "Extracted 35 Q&A items from internal survey", done: true }
      ],
      nextAction: "レビュー完了→Dify登録",
      nextActionEn: "Review completion → Register in Dify",
      lastUpdated: "2026/3/15",
      lastUpdatedNote: "ナレッジ追加",
      lastUpdatedNoteEn: "Knowledge added"
    },
    {
      name: "チャット通知自動化システム",
      nameEn: "Chat Notification Automation",
      description: "Chatworkのメッセージを自動でTeamsに通知+未対応時は自動返信",
      descriptionEn: "Auto-forward Chatwork messages to Teams + auto-reply when unresponded",
      status: "testing",
      statusLabel: "テスト中",
      statusLabelEn: "Testing",
      progress: 70,
      url: null,
      detail: {
        overview: "クライアントからChatworkに届いたメッセージを、社内のTeamsに自動通知するシステム。メンション連動、30分未対応時の自動返信、営業時間内外の文面切替など高度な制御を実装。",
        overviewEn: "A system that auto-forwards client messages from Chatwork to Teams. Features include mention sync, 30-min auto-reply for unresponded messages, and business hours message switching.",
        background: "Chatworkを定期的に確認しないとメッセージを見逃すリスクがあり、クライアント対応の遅延が発生していた。普段使っているTeamsで気づける仕組みが必要だった。",
        backgroundEn: "Risk of missing Chatwork messages without constant checking, causing delayed client responses. Needed a way to catch messages via Teams.",
        targetUsers: "クライアント対応を行う社員",
        targetUsersEn: "Staff handling client communications",
        tools: ["Python", "FastAPI", "Railway", "Power Automate"],
        impact: {
          before: "Chatworkを定期的に確認 → 見逃し・対応遅延のリスク",
          beforeEn: "Periodically check Chatwork → risk of missed messages & delays",
          after: "Teamsに自動通知 + 未対応時は自動返信でクライアント安心",
          afterEn: "Auto-notify on Teams + auto-reply reassures clients",
          savedTime: "クライアント対応の見逃しゼロ化",
          savedTimeEn: "Zero missed client messages"
        },
        period: "2026年3月4日〜",
        periodEn: "Mar 4, 2026 –"
      },
      history: [
        { text: "仕様設計（v1→v8まで改訂）", textEn: "Spec design (revised v1 to v8)", done: true },
        { text: "Python / FastAPI開発", textEn: "Python / FastAPI development", done: true },
        { text: "署名検証・通知制限・自動返信実装", textEn: "Signature verification, rate limiting & auto-reply", done: true },
        { text: "Railwayデプロイ", textEn: "Railway deployment", done: true },
        { text: "2社でPoCテスト開始", textEn: "PoC testing started with 2 clients", done: true },
        { text: "スレッド化調査（PA権限制限により見送り）", textEn: "Threading investigation (deferred due to PA permission limits)", done: true, actualHours: 1.0 }
      ],
      nextAction: "PoCテスト継続・他クライアント展開",
      nextActionEn: "Continue PoC testing & expand to other clients",
      lastUpdated: "2026/3/16",
      lastUpdatedNote: "スレッド化調査完了（見送り）",
      lastUpdatedNoteEn: "Threading investigation completed (deferred)"
    },
    {
      name: "案件マッチングメール自動配信",
      nameEn: "Job Matching Auto-Mailer",
      description: "案件情報を入力するだけで対象者全員にオファーメールを自動配信",
      descriptionEn: "Auto-send offer emails to all candidates by simply entering job details",
      status: "building",
      statusLabel: "構築中",
      statusLabelEn: "Building",
      progress: 75,
      url: null,
      detail: {
        overview: "案件発生時に、AIチャットへ案件情報を入力するだけで、オファーメールの作成・対象者の抽出・一斉配信・エントリー回答の集約まで自動で完結するシステム。",
        overviewEn: "A system that automates the entire flow—from email creation, candidate extraction, bulk sending, to response collection—just by entering job details into an AI chat.",
        background: "案件発生のたびに手動でメールを作成・数百名の登録人材に送信・回答を集計しており、担当者の大きな負担になっていた。",
        backgroundEn: "Each job opening required manually composing emails, sending to hundreds of registered candidates, and tallying responses—a heavy burden on staff.",
        targetUsers: "案件アサイン担当者",
        targetUsersEn: "Job assignment managers",
        tools: ["Dify", "Make", "kintone", "Outlook", "Microsoft Forms"],
        impact: {
          before: "手動でメール作成・送信・回答集計（数時間/回）",
          beforeEn: "Manual email creation, sending & response collection (hours per job)",
          after: "AIチャットに入力1回で全自動（数分）",
          afterEn: "Fully automated with one AI chat input (minutes)",
          savedTime: "1回あたり数時間の作業を数分に短縮",
          savedTimeEn: "Hours of work reduced to minutes per job"
        },
        period: "2026年3月11日〜",
        periodEn: "Mar 11, 2026 –"
      },
      history: [
        { text: "仕様書v1.0作成", textEn: "Spec v1.0 created", done: true },
        { text: "Difyワークフロー構築（12項目入力→LLM→メール生成）", textEn: "Dify workflow (12 inputs → LLM → email generation)", done: true },
        { text: "Makeシナリオ構築（kintone→Outlook一括送信）", textEn: "Make scenario (kintone → Outlook bulk send)", done: true },
        { text: "kintone API連携・BCC方式実装", textEn: "kintone API integration & BCC implementation", done: true },
        { text: "結合テスト成功", textEn: "Integration test passed", done: true }
      ],
      nextAction: "担当者確認→パイロット",
      nextActionEn: "Manager review → Pilot test",
      lastUpdated: "2026/3/15",
      lastUpdatedNote: "結合テスト成功",
      lastUpdatedNoteEn: "Integration test passed"
    },
    {
      name: "AI人材マッチングシステム",
      nameEn: "AI Talent Matching System",
      description: "AIが登録人材のスキル・経験を分析し、最適な候補者を自動提案",
      descriptionEn: "AI analyzes candidate skills & experience to auto-suggest best matches",
      status: "designed",
      statusLabel: "設計済み",
      statusLabelEn: "Designed",
      progress: 20,
      url: null,
      detail: {
        overview: "案件の要件に対して、AIが登録人材のスキル・経験・稼働余力を分析し、最適な候補者をスコアリングして提案するシステム。Mini版（全員配信）の発展形。",
        overviewEn: "A system where AI analyzes registered candidates' skills, experience, and availability against job requirements, scoring and suggesting the best matches. An evolution of the Mini version (bulk send).",
        background: "Mini版では全登録人材に一斉送信だが、本来は案件要件に合った人材を効率的に絞り込みたい。AIによる候補者の自動マッチングが求められていた。",
        backgroundEn: "The Mini version sends to all candidates, but ideally we want to efficiently narrow down to those matching job requirements. AI-powered auto-matching was needed.",
        targetUsers: "案件アサイン担当者",
        targetUsersEn: "Job assignment managers",
        tools: ["Dify", "Make", "kintone", "SharePoint", "Azure AD"],
        impact: {
          before: "担当者が経験と勘で候補者を選定（属人的・時間がかかる）",
          beforeEn: "Managers select candidates by experience and intuition (person-dependent, time-consuming)",
          after: "AIがスコアリングした候補者リストを自動提示",
          afterEn: "AI auto-presents a scored candidate list",
          savedTime: "候補者選定の時間短縮・属人化の解消",
          savedTimeEn: "Faster candidate selection, reduced person-dependency"
        },
        period: "2026年3月10日〜",
        periodEn: "Mar 10, 2026 –"
      },
      history: [
        { text: "仕様書v1.2作成", textEn: "Spec v1.2 created", done: true },
        { text: "Azure AD承認取得", textEn: "Azure AD approval obtained", done: true },
        { text: "kintone API取得・名前マッチング検証", textEn: "kintone API integration & name matching test", done: true }
      ],
      nextAction: "Mini完了後に着手",
      nextActionEn: "Start after Mini completion",
      lastUpdated: "2026/3/10",
      lastUpdatedNote: "kintone検証完了",
      lastUpdatedNoteEn: "kintone verification done"
    },
    {
      name: "Slack通知自動化システム",
      nameEn: "Slack Notification Automation",
      description: "SlackのメッセージをTeamsに自動通知（Chatwork版の姉妹システム）",
      descriptionEn: "Auto-forward Slack messages to Teams (sister system of Chatwork version)",
      status: "designed",
      statusLabel: "設計済み",
      statusLabelEn: "Designed",
      progress: 15,
      url: null,
      detail: {
        overview: "Chatwork版と同じ仕組みを、Slackを使っているクライアント向けに提供。Chatwork版のコードを約7割流用し、Slack固有の仕様に対応する部分のみ新規開発。",
        overviewEn: "Provides the same mechanism as the Chatwork version for Slack-using clients. Reuses ~70% of Chatwork version code, with new development only for Slack-specific features.",
        background: "一部のクライアントはSlackでやり取りしており、Chatwork版と同様の通知自動化ニーズがあった。",
        backgroundEn: "Some clients communicate via Slack and had the same notification automation needs as the Chatwork version.",
        targetUsers: "Slackでやり取りしているクライアントを担当する社員",
        targetUsersEn: "Staff managing Slack-based client communications",
        tools: ["Python", "FastAPI", "Railway", "Slack API", "Power Automate"],
        impact: {
          before: "Slackを定期的に確認 → 見逃し・対応遅延のリスク",
          beforeEn: "Periodically check Slack → risk of missed messages & delays",
          after: "Teamsに自動通知 + 未対応時は自動返信",
          afterEn: "Auto-notify on Teams + auto-reply when unresponded",
          savedTime: "Chatwork版と同等の効果を見込む",
          savedTimeEn: "Expected impact equivalent to Chatwork version"
        },
        period: "2026年3月9日〜",
        periodEn: "Mar 9, 2026 –"
      },
      history: [
        { text: "仕様書v1作成（Chatwork版ベース）", textEn: "Spec v1 created (based on Chatwork version)", done: true }
      ],
      nextAction: "確認→コーディング",
      nextActionEn: "Review → Coding",
      lastUpdated: "2026/3/9",
      lastUpdatedNote: "仕様書作成",
      lastUpdatedNoteEn: "Spec created"
    },
    {
      name: "工数分析レポート自動作成",
      nameEn: "Work-Hours Analysis Report Generator",
      description: "工数CSVから業務工数を分析し、クライアント向け＋社内専用レポートを自動生成",
      descriptionEn: "Analyze work-hours CSV and auto-generate client & internal reports",
      status: "building",
      statusLabel: "構築中",
      statusLabelEn: "Building",
      progress: 25,
      url: null,
      detail: {
        overview: "クライアントの月次作業ログCSVから、業務別・担当者別・月初中末別の工数分析を行い、クライアント向けレポート（提出可能）と社内専用レポート（提出禁止）の2種類を自動生成するDifyワークフロー。",
        overviewEn: "A Dify workflow that analyzes monthly work-log CSVs by task, worker, and timing (early/mid/late month), generating two reports: client-facing (submittable) and internal-only (confidential).",
        background: "工数データの集計・レポート作成に時間がかかっており、カスタムGPTで原型を運用していたが、社内ツール化・自動配信のためDifyに移植。",
        backgroundEn: "Work-hours reporting was time-consuming. A Custom GPT prototype was in use, but migration to Dify was needed for internal tooling and automated distribution.",
        targetUsers: "クライアント責任者・管理部門",
        targetUsersEn: "Client managers & administration",
        tools: ["Dify", "LLM", "Python", "Power Automate"],
        impact: {
          before: "カスタムGPTに手動でCSVアップロード→レポート手作業で整形",
          beforeEn: "Manually upload CSV to Custom GPT → manually format reports",
          after: "Difyワークフローで分析→Word生成→SharePoint保存→Teams通知まで自動化",
          afterEn: "Automated analysis via Dify workflow → Word generation → SharePoint → Teams notification",
          savedTime: "レポート作成の工数を大幅削減",
          savedTimeEn: "Significant reduction in report creation effort"
        },
        period: "2026年3月13日〜",
        periodEn: "Mar 13, 2026 –"
      },
      history: [
        { text: "カスタムGPTで原型を制作済み", textEn: "Prototype built with Custom GPT", done: true },
        { text: "Dify化設計（アーキテクチャ・ワークフロー・コード・プロンプト）", textEn: "Dify migration design (architecture, workflow, code, prompts)", done: true },
        { text: "設計レビュー・Code①改善版作成・検証完了", textEn: "Design review, improved Code① created & verified", done: true },
        { text: "LLMプロンプト完成版作成", textEn: "Finalized LLM prompts", done: true }
      ],
      nextAction: "Difyノード構築→テスト",
      nextActionEn: "Build Dify nodes → Test",
      lastUpdated: "2026/3/15",
      lastUpdatedNote: "プロンプト完成",
      lastUpdatedNoteEn: "Prompts finalized"
    },
    {
      name: "AI活用相談ボット",
      nameEn: "AI Consultation Bot",
      description: "社員からの業務効率化相談をAIが一次ヒアリングし、構造化して管理するDX相談受付システム",
      descriptionEn: "AI-powered first-interview bot that structures employee automation consultation requests",
      status: "building",
      statusLabel: "構築中",
      statusLabelEn: "Building",
      progress: 20,
      url: null,
      detail: {
        overview: "社員が業務効率化・自動化の相談をAIチャットボットに入力すると、Dify上のAIが対話形式で必要情報をヒアリングし、構造化テキストを生成。社員本人が内容を確認・修正した後、MakeでSharePoint Listに保存しTeamsで通知する社内DX相談受付システム。",
        overviewEn: "An internal DX consultation system where employees submit automation requests via Dify AI chatbot. The AI conducts structured interviews, generates organized summaries, gets employee confirmation, then saves to SharePoint List via Make and notifies via Teams.",
        background: "社員ごとに説明能力・業務整理能力が異なるため、相談内容のヒアリングが非効率になり、再ヒアリングが多発していた。AIによる標準化されたヒアリングで解決を図る。",
        backgroundEn: "Employees vary in their ability to articulate needs, making consultation interviews inefficient with frequent re-interviews. Standardized AI interviews aim to solve this.",
        targetUsers: "業務効率化を相談したい社員全員",
        targetUsersEn: "All employees seeking automation consultation",
        tools: ["Dify", "Make", "SharePoint List", "GitHub Pages"],
        impact: {
          before: "相談内容が整理されず再ヒアリングが多発（1件30分〜1時間）",
          beforeEn: "Unstructured consultations requiring frequent re-interviews (30 min – 1 hour each)",
          after: "AIが対話で必要情報を漏れなく収集・構造化（数分）",
          afterEn: "AI collects and structures all necessary info via dialogue (minutes)",
          savedTime: "ヒアリング・要件整理の工数を大幅削減",
          savedTimeEn: "Significant reduction in interview & requirements organization effort"
        },
        period: "2026年3月15日〜",
        periodEn: "Mar 15, 2026 –"
      },
      history: [
        { text: "要件定義・設計相談テキスト作成", textEn: "Requirements definition & design document created", done: true },
        { text: "ヒアリング項目設計（Q0〜Q11）", textEn: "Interview items designed (Q0-Q11)", done: true },
        { text: "確認ループ・構造化出力の設計", textEn: "Confirmation loop & structured output designed", done: true },
        { text: "設計書完成（アーキテクチャ・DB・Make・Dify・埋め込み仕様）", textEn: "Design doc completed (architecture, DB, Make, Dify, embed spec)", done: true }
      ],
      nextAction: "実装着手（Dify→SharePoint→Make→GitHub Pages）",
      nextActionEn: "Start implementation (Dify → SharePoint → Make → GitHub Pages)",
      lastUpdated: "2026/3/15",
      lastUpdatedNote: "設計書完成",
      lastUpdatedNoteEn: "Design doc completed"
    },
    {
      name: "議事録自動作成ツール",
      nameEn: "Auto Meeting Minutes Generator",
      description: "会議の文字起こしから議事録を自動生成",
      descriptionEn: "Auto-generate meeting minutes from transcripts",
      status: "planned",
      statusLabel: "構想中",
      statusLabelEn: "Planned",
      progress: 5,
      url: null,
      detail: {
        overview: "会議の文字起こしデータから、要点・決定事項・アクションアイテムを整理した議事録を自動生成するツール。現在カスタムGPTで原型を制作済み。",
        overviewEn: "A tool that auto-generates meeting minutes with key points, decisions, and action items from meeting transcripts. Prototype built with Custom GPT.",
        background: "会議後の議事録作成に30分〜1時間かかるケースがあり、作成の負担や品質のばらつきが課題だった。",
        backgroundEn: "Creating meeting minutes took 30 min to 1 hour, with inconsistent quality being a challenge.",
        targetUsers: "会議参加者・議事録作成担当者",
        targetUsersEn: "Meeting participants & minute-takers",
        tools: ["カスタムGPT", "→ Dify / Make（移行検討中）"],
        impact: null,
        period: "構想段階",
        periodEn: "Planning stage"
      },
      history: [
        { text: "カスタムGPTで原型を制作済み", textEn: "Prototype built with Custom GPT", done: true },
        { text: "プロジェクト登録", textEn: "Project registered", done: false }
      ],
      nextAction: "仕様整理→方針決定",
      nextActionEn: "Organize specs → Decide approach",
      lastUpdated: "2026/3/13",
      lastUpdatedNote: "プロジェクト登録",
      lastUpdatedNoteEn: "Project registered"
    },
    {
      name: "決算レポート自動作成",
      nameEn: "Financial Report Generator",
      description: "決算データから報告書レポートを自動生成",
      descriptionEn: "Auto-generate financial reports from accounting data",
      status: "planned",
      statusLabel: "構想中",
      statusLabelEn: "Planned",
      progress: 5,
      url: null,
      detail: {
        overview: "決算データから報告書レポートを自動生成するツール。現在カスタムGPTで原型を制作済み、Dify/Make等へのアップデートを検討中。",
        overviewEn: "A tool that auto-generates financial reports from accounting data. Prototype built with Custom GPT; considering migration to Dify/Make.",
        background: "決算レポートの作成に時間がかかっており、定型的な部分をAIで効率化したいニーズがあった。",
        backgroundEn: "Creating financial reports was time-consuming, and there was a need to automate routine parts using AI.",
        targetUsers: "経理・会計担当者",
        targetUsersEn: "Accounting & finance staff",
        tools: ["カスタムGPT", "→ Dify / Make（移行検討中）"],
        impact: null,
        period: "構想段階",
        periodEn: "Planning stage"
      },
      history: [
        { text: "カスタムGPTで原型を制作済み", textEn: "Prototype built with Custom GPT", done: true },
        { text: "プロジェクト登録", textEn: "Project registered", done: false }
      ],
      nextAction: "仕様整理→方針決定",
      nextActionEn: "Organize specs → Decide approach",
      lastUpdated: "2026/3/13",
      lastUpdatedNote: "プロジェクト登録",
      lastUpdatedNoteEn: "Project registered"
    },
    {
      name: "AIプロジェクトスケジューラー",
      nameEn: "AI Project Scheduler",
      description: "AIがプロジェクト状況を分析し、Outlook予定表の空き時間に作業予定を自動配置する1週間ローリングスケジューラー",
      descriptionEn: "AI analyzes project status and auto-schedules work blocks into Outlook calendar free slots (1-week rolling)",
      status: "building",
      statusLabel: "構築中",
      statusLabelEn: "Building",
      progress: 85,
      url: null,
      detail: {
        overview: "BOF-AI-Dashboardのプロジェクトデータ（data.js）をAIが分析し、優先順位を判定。Outlook予定表の空き時間に作業予定を自動配置する1週間ローリングスケジューラー。毎朝8:00に自動実行し、状況変化に応じて予定を再評価・更新する。",
        overviewEn: "AI analyzes project data (data.js) from BOF-AI-Dashboard, determines priorities, and auto-schedules work blocks into Outlook calendar free slots. Runs daily at 8:00 AM with rolling 1-week re-evaluation.",
        background: "複数のAIプロジェクトを同時進行する中、どのプロジェクトにいつ時間を割くべきかの判断が属人的で、着手の優先順位付けに毎朝時間を使っていた。",
        backgroundEn: "While managing multiple AI projects, deciding which to work on and when was person-dependent, taking time each morning to prioritize.",
        targetUsers: "AIプロジェクト担当者（菅田）",
        targetUsersEn: "AI project manager (Sugata)",
        tools: ["Make", "OpenAI", "Microsoft Graph API", "GitHub Pages"],
        impact: {
          before: "毎朝手動でプロジェクト状況を確認し、何に取り組むか判断（15〜30分）",
          beforeEn: "Manually review project status each morning and decide what to work on (15-30 min)",
          after: "AIが自動で優先順位を判定し、Outlook予定に作業予定を配置（自動）",
          afterEn: "AI auto-prioritizes and schedules work blocks in Outlook (automated)",
          savedTime: "毎朝の判断・計画時間を削減 + プロジェクト停滞の防止",
          savedTimeEn: "Reduced daily planning time + prevention of project stagnation"
        },
        period: "2026年3月15日〜",
        periodEn: "Mar 15, 2026 –"
      },
      history: [
        { text: "仕様書v1.1作成", textEn: "Spec v1.1 created", done: true },
        { text: "AIスケジューリングプロンプト作成", textEn: "AI scheduling prompt created", done: true },
        { text: "作業時間推定方式・工数自動計測仕様の策定", textEn: "Work time estimation & auto time-tracking spec defined", done: true },
        { text: "Make構築手順書作成", textEn: "Make build guide created", done: true },
        { text: "Makeシナリオ構築（HTTP+API Call+OpenAI+Iterator+Create Event）", textEn: "Make scenario build (HTTP+API Call+OpenAI+Iterator+Create Event)", done: true, actualHours: 5.5 },
        { text: "Schedulerトリガー+toDelete自動削除+シナリオON", textEn: "Scheduler trigger + toDelete auto-delete + scenario activation", done: false },
        { text: "重複予定一括削除・toDelete設計", textEn: "Bulk delete duplicate events & toDelete flow design", done: true, actualHours: 0.5 },
        { text: "toDelete削除フロー実装（Router+Filter）・Scheduler設定・Coreプラン契約", textEn: "toDelete flow implementation (Router+Filter), Scheduler config & Core plan upgrade", done: true, actualHours: 1.0 }
      ],
      nextAction: "Phase Cテスト（再評価テスト）→シナリオON",
      nextActionEn: "Phase C test (re-evaluation) → Activate scenario",
      lastUpdated: "2026/3/17",
      lastUpdatedNote: "toDeleteフロー実装完了・Scheduler設定済み",
      lastUpdatedNoteEn: "toDelete flow implemented & Scheduler configured"
    },
    {
      name: "AI活用プロジェクトダッシュボード",
      nameEn: "AI Project Dashboard",
      description: "菅田が担当するAI活用プロジェクトの進捗・ステータスを一覧管理するWebダッシュボード",
      descriptionEn: "Web dashboard to track progress & status of Sugata's AI projects",
      status: "live",
      statusLabel: "運用中",
      statusLabelEn: "Live",
      progress: 100,
      url: "https://sugatatakuma.github.io/bof-ai-dashboard/internal.html",
      detail: {
        overview: "菅田が担当するAI活用プロジェクトの進捗・ステータス・作業歴・次のアクションを一覧で確認できるWebダッシュボード。カード/リスト切替、検索・フィルター・ソート、日英切替、印刷対応など多機能。GitHub Pagesで社内公開中。",
        overviewEn: "A web dashboard to view progress, status, history, and next actions for Sugata's AI projects. Features card/list views, search, filter, sort, language toggle (JP/EN), and print support. Published via GitHub Pages.",
        background: "複数のAI活用プロジェクトを同時に担当する中、各プロジェクトの進捗やステータスを一元的に把握・共有する手段がなかった。",
        backgroundEn: "While managing multiple AI projects simultaneously, there was no centralized way to track and share progress and status.",
        targetUsers: "社内メンバー・マネージャー",
        targetUsersEn: "Internal staff & managers",
        tools: ["HTML", "CSS", "JavaScript", "GitHub Pages"],
        impact: {
          before: "プロジェクト状況を個別に口頭やチャットで確認",
          beforeEn: "Check project status individually via verbal or chat communication",
          after: "ダッシュボードでリアルタイムに一覧確認",
          afterEn: "View all project statuses in real-time on the dashboard",
          savedTime: "進捗共有・報告の工数を削減",
          savedTimeEn: "Reduced effort for progress sharing & reporting"
        },
        period: "2026年3月13日〜3月14日",
        periodEn: "Mar 13 – Mar 14, 2026"
      },
      history: [
        { text: "HTML/CSS/JS基盤構築", textEn: "HTML/CSS/JS foundation build", done: true },
        { text: "data.js共有データ管理化", textEn: "Shared data management via data.js", done: true },
        { text: "検索・フィルター・ソート実装", textEn: "Search, filter & sort implementation", done: true },
        { text: "日英切替・レスポンシブ・印刷対応", textEn: "Language toggle, responsive & print support", done: true },
        { text: "GitHub Pages公開・社内共有", textEn: "Published on GitHub Pages & shared internally", done: true }
      ],
      nextAction: "運用中（データ更新のみ）",
      nextActionEn: "In operation (data updates only)",
      lastUpdated: "2026/3/15",
      lastUpdatedNote: "機能追加",
      lastUpdatedNoteEn: "Feature added"
    }
  ]
};
